# Generated by Django 5.2.6 on 2025-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_studyhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('book', 'Book'), ('practice', 'Practice'), ('exam', 'Exam')], default='lesson', max_length=20),
        ),
    ]
